version: "3"
services:
  postgres:
    container_name: meal-planner
    image: postgres:15-alpine
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=planner
      - POSTGRES_PASSWORD=planner
      - POSTGRES_DB=planner


  auth:
    container_name: Auth
    build: ./auth/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AUTH0_CLIENT_ID=JIFNsmiMxECEs0ZzWAsSxJCn1uB9Z2Iv
      - AUTH0_CLIENT_SECRET=1ehee6u__68_0xxiebZ8mkE5QZtPUpmd5mGlMvYAZZIdk--PcBsNo5lUAYPca6ET
      - AUTH0_DOMAIN=dev-mos1yyaskfoaocbo.us.auth0.com
      - APP_SECRET_KEY=random
  
volumes:
  db:
    driver: local
